Fix NoSuchMethodError when calling CameraXHelper.createCameraProvider without useCases (#546)
* Fix NoSuchMethodError No virtual method createCameraProvider caused by method kotlin optional argument

* Fix typo in readme

* Use JvmOverloads